FROM python:3.6

RUN apt-get update && apt-get install -y \
  libfftw3-dev \
  libhdf5-serial-dev
COPY ./requirements.txt ./requirements-manual.txt /
RUN pip install --no-cache-dir -r /requirements.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf ~/.cache/pip
RUN mkdir /samples /logs

WORKDIR /malgazer
CMD ${COMMAND}
