FROM python:3

#RUN cd /; git clone https://github.com/keithjjones/malgazer.git
COPY ./requirements.txt /
RUN pip install -r /requirements.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /malgazer/flask
ENV FLASK_APP=malgazer.py
CMD ["flask", "run", "--host 0.0.0.0", "--port 8080"]
