FROM python:3

RUN apt-get update && apt-get install -y \
  libfftw3-dev
COPY ./requirements.txt ./requirements-manual.txt /
RUN pip install -r /requirements.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN mkdir /samples

WORKDIR /malgazer
CMD ${COMMAND}
