FROM python:3

#RUN cd /; git clone https://github.com/keithjjones/malgazer.git
COPY ./requirements.txt /
RUN pip install -r /requirements.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /malgazer/flask
ENV FLASK_APP=malgazer.py
#ENV FLASK_ENV=development
#CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]
CMD ["gunicorn", "-w 10", "-b 127.0.0.1:8080", "malgazer:app"]
