FROM python:3

RUN apt-get update && apt-get install -y \
  libfftw3-dev
COPY ./requirements.txt ./requirements-manual.txt /
RUN pip install -r /requirements.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN mkdir /samples

WORKDIR /malgazer
ENV FLASK_APP=docker.api.api
ENV FLASK_ENV=development
# Below is for development.
CMD ["flask", "run", "--host=0.0.0.0", "--port=8888"]
# Below is for production.
#CMD ["gunicorn", "-w 10", "-b 0.0.0.0:8888", "docker.api.api:app"]

